### ISSUE TITLE
DB queue size ballooning

### ISSUE THREAD

**Issue by mgoodsell91** [PokemonGoMap/PokemonGo-Map#1074]
The DB queue ballooned to nearly 3000 after "pthread_cond_wait: Resource busy" error. Ive never had a warning about it but the queue size before
## Expected Behavior
Queue size stays below 50

## Current Behavior
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
pthread_cond_wait: Resource busy
2016-08-31 10:03:38,018 [    db-updater-0][        models][ WARNING] DB queue is > 50 (@2910); try increasing --db-threads

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment

* Version used:latest pull
* Environment name and version (e.g. Python 2.7):Python 2.7
* Operating System and version (desktop or mobile):Mac osx 10.11

**Comment by nothize** [comment]
Try to specify -nk (no pokestop) and -ng (no gym) because stop visibility is around 900m while the scanning circle is having 70m radius.

**Comment by mgoodsell91** [comment]
Cheers for the tip Ill try that. but Ive never had this issue before, not even warnings so im a bit concerned that its gone from nothing at all to just under a 3000 queue in seconds

**Comment by jjmakin** [comment]
I have tried this and it certainly helps, but it feels hacky.

**Comment by mgoodsell91** [comment]
Ha, yeah absolutely.

**Comment by ardeaf** [comment]
I have this same problem.  However, it happens over the course of hours rather than seconds.  Inevitably I eventually run into the queue size becoming unmanageable. I went to bed with the server running, and woke up with a queue size of >4000.

Currently using MySQL, with max connections at 500.  Doing a test run right now with --db-threads 50.  Amount of workers is around 280 (there are some banned accounts that I haven't removed from this list of workers).  Using -ss spawns.json.  My config has disabled Pokestops and Gyms.  I am running the server on a remote host behind a VPN on Ubuntu 14.04. 

Could it be a hardware issue?

**Comment by pyr0ball** [comment]
Not a bug. this is an implementation/configuration issue. Please post on the [support forum](http://pokemongo-map.me) or on discord for help
