### ISSUE TITLE
Snorlax is classified as "Rare"

### ISSUE THREAD

**Issue by DrAtari** [PokemonGoMap/PokemonGo-Map#1296]
Snorlax is classified as "Rare", thus it doesn't show a notification when PokemonGo-Map is setup to notify about "Very Rare" and "Ultra Rare" Pokemon. Is it supposed to be like that, or is it a bug?

**Comment by skaforey** [comment]
I found this very strange as well, not sure how the rarities were decided.

**Comment by filippounitn** [comment]
I agree, it should be very rare istead of rare.

**Comment by DiscoTim** [comment]
rarity i think is a large part subjective, and depends on your location.  i'd like to see a system where it calculates the rarity based on your data of previous sightings or a combination of both.

**Comment by FrostTheFox** [comment]
I'm not 100% sure what rarity was originally determined by, but it really should be taken with a grain of salt (except when it comes to things like pidgey/weedle.)

**Comment by SoonDead** [comment]
Although Rarity is location dependant, there is more or less a general consensus about really valuable pokémon.

Snorlax is REALLY valuable.

Since notification should notify about what you really want to collect, you generally want to know if there is a snorlax around.

Since most people don't want to spend 15 minutes every time they set this up on a new mobile, they just check the 2 top rarities. This is helpful and is generally ok. Except one would expect *the* snorlax to be there.

**Comment by CatsFaninLex** [comment]
Which file do I need to edit to change this?

**Comment by DiscoTim** [comment]
@CatsFaninLex \static\data\pokemon.json then npm install

**Comment by crckdns** [comment]
the Spawnrate was changed... snorlax is pretty common now, same with other "rare" spawns from days earlier

**Comment by FrostTheFox** [comment]
I've bumped it up to very rare, although in reality these cant ever be close to accurate without location based checking. #1305

**Comment by 3Trace** [comment]
And Dratini is "common" or "uncommon" one or the other.
