### ISSUE TITLE
No pokemon icons for Lured Pokestops

### ISSUE THREAD

**Issue by alangregory** [PokemonGoMap/PokemonGo-Map#131]
## Expected Behavior

Show pokemon icon from lured pokestops on map.
Wild pokemons are working normaly
## Current Behavior

![captura de tela de 2016-08-08 08 37 51](https://cloud.githubusercontent.com/assets/1170503/17478634/a439685e-5d43-11e6-9027-6ee79f0c373c.png)
![captura de tela de 2016-08-08 08 42 08](https://cloud.githubusercontent.com/assets/1170503/17478707/13b661be-5d44-11e6-86d6-b2fee4aee0c1.png)

## Your Environment

* Version used: 9dd738b
* Environment name and version: Python 2.7.12
* Operating System and version: Ubuntu Server 16.04

**Comment by chimpy** [comment]
I have this issue too.

Version: 78fee4a
OS: Ubuntu Server 14.04

**Comment by chuyskywalker** [comment]
A lure being present does not guarantee a pokemon has been lured and should be shown. I also know that this _is_ working since:

![2016-08-08 07_30_58-pokemon go map](https://cloud.githubusercontent.com/assets/131800/17483255/2c24c86c-5d3a-11e6-836e-6f8d54e71eac.png)

Is a SS on my map about 1km from my scan points.

**Comment by blastagator** [comment]
Same issue.  Clicking the pokestop says the name of the pokemon that is currently lured, but the actual icon for the lured pokemon is not there.  Issue present on Ubuntu and BBQLinux.

**Comment by chuyskywalker** [comment]
Ah, I see.

**Comment by Chlodochar** [comment]
See https://github.com/PokemonGoMap/PokemonGo-Map/pull/194
