### ISSUE TITLE
Database update breaking functionality

### ISSUE THREAD

**Issue by jccwright** [PokemonGoMap/PokemonGo-Map#1416]
## Expected Behavior

Something in the database update from v7 to v8 is causing a breaking change

## Current Behavior

Accounts are getting "iced" because of an "Exception in search_worker under account *********** Exception message: (1054, u"Unknown column 't1.individual_stamina' in 'field list'")
![pokemongomapdberror](https://cloud.githubusercontent.com/assets/13989827/18957117/db5ba890-862b-11e6-9c5d-0e1fb23ad71f.png)

## Possible Solution

Unsure atm, will continue to investigate and update.

## Steps to Reproduce (for bugs)

1. See screenshot above
2. Happened after recent fetch (npm install and pip install --upgrade -r requirements.txt performed)
3.
4.

## Context

Map no longer functional and all searches failing. Accounts getting iced. 

## Your Environment

* Version used: v3.2.0-45-g9b3927e
* Environment name and version (e.g. Python 2.7): Python 2.7.12; Node v7.0.0-nightly20160812ca6363b8ae
* Operating System and version (desktop or mobile): Windows 10 desktop HP Envy TouchSmart dual quad core i7 w/ 16GB Ram

**Comment by paulharman** [comment]
Same sort of issue here - InternalError: (1054, u"Unknown column 't1.individual_defense' in 'field list'")

**Comment by Thyllz** [comment]
Got the same issue as well: InternalError: (1054, u"Unknown column 't1.individual_stamina' in 'field list'").
This happend on restart after update/fetch (npm install / pip install -r requirements.txt --upgrade )
Database said it was upgrading to v8 and nothing more happend in that window.

**Comment by traschke** [comment]
Getting this one

OperationalError: (1054, "Unknown column 't1.move_2' in 'field list'")

**Comment by PenguinsFlyGood** [comment]
You have to add those columns to the pokemon table manually, worked for me

**Comment by aldarund** [comment]
Thats because of long migration for IV. if u have existing db with pokemons - it will take long time depending on number of pokemon. For example for 8m records in pokemon table it took for me  ~7h for migration. While migration is working  other workers will have this error. 
If u cancel it before it actually finished -> unlucky. Db version got updated, but the columns wasnt actually added.
Why so slow - because mysql stupid. To add 5 columns into existing table it do following.
1. Create temp table with 1 of this 5 new column 
2. Copy existing data into it
3. Delete initial table and rename new one to it.
And it do it for every column. So basically it copy the whole pokemon table 5 times. GG WP

**Comment by primaxius** [comment]
This was cause by you guys running 2 instances at same time right after an update.  You crashed the database migrator which updates the DB to a new version.

You now have 2 options to fix this.

- quick method  is to clear your DB,  Run 1 instance only and add `-cd` to your command line. Once it runs and the DB is cleared you stop said instance and remove the `-cd` again immediately and start all your instances.

- slow method will save your data however is more intense and will require you to run a query on the database. You will need to delete columns in the BD that may have been partially added then run another query to add them all again. This will take time so be patient, usually a few minutes.
 <script src="https://gist.github.com/primaxius/126fe4b8674cd284d6f97a690f3ba90d.js"></script>
