### ISSUE TITLE
OperationalError: no such column: t1.individual_attack

### ISSUE THREAD

**Issue by SnakeIz** [PokemonGoMap/PokemonGo-Map#1430]
.

**Comment by jpdus** [comment]
Same error here

**Comment by averylarry** [comment]
I gotta think that's a db migration problem.  You're missing a column in your db.  If this is happening the first time you start up after doing an update, then you should close all the extra workers and allow the first runserver.py to finish -- it MIGHT still be trying to migrate the database.
Otherwise you'll have to try and get help fixing your db, or the easiest thing to do is just clear your database and start with an empty db.

**Comment by jpdus** [comment]
@averylarry : Thanks, that's it. For reference (dropping the DB is no option because I need it for spawn point scanning), I found the solution to fix the DB [here](https://github.com/PokemonGoMap/PokemonGo-Map/issues/1416). 
It would probably be good to show a warning for future migrations which lead to downtime/errors and which take a lot of time...

**Comment by averylarry** [comment]
A warning nobody will look at?  j/k  -- sorta
Seriously though -- there's only so much that can be done when people pull uncommitted PRs and change the db schema versions on their own and then try to revert and move forward.  For those with really big DBs that would take a long time one would hope they would understand what's going on and realize that a db version change / migration means planning and patience.

**Comment by FrostTheFox** [comment]
This was cause by you guys running 2 instances at same time right after an update. You crashed the database migrator which updates the DB to a new version.

You now have 2 options to fix this.

quick method is to clear your DB, Run 1 instance only and add -cd to your command line. Once it runs and the DB is cleared you stop said instance and remove the -cd again immediately and start all your instances.

slow method will save your data however is more intense and will require you to run a query on the database. You will need to delete columns in the BD that may have been partially added then run another query to add them all again. This will take time so be patient, usually a few minutes.

https://gist.github.com/primaxius/126fe4b8674cd284d6f97a690f3ba90d

#1416. Please search issues before making a new one.
