### ISSUE TITLE
Release misses frontend assets, server cannot start

### ISSUE THREAD

**Issue by aldafu** [PokemonGoMap/PokemonGo-Map#1445]
I downloaded the 3.2.0 release tarball and installed the requirements.

Starting the server fails with:
2016-10-03 13:06:19,287 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server

The static/dist/ directory is indeed not in the tarball.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by BaIthamel** [comment]
Missclick :P

**Comment by ultrafunkamsterdam** [comment]
Remove the entire folder
install grunt-cli
clone again

**Comment by FrostTheFox** [comment]
The tarball is compiled from source by github. The releases are only done because we receive requests for them, they quickly become outdated and as such we recommend just pulling from develop branch. The latest release I elected to not compile the frontend assets, I suppose next release I can do it, it's just a massive waste of time for me to do when it takes so little time for one to do it themselves.

**Comment by FrostTheFox** [comment]
Actually, I can update the release with the frontend assets built.

**Comment by FrostTheFox** [comment]
Updated

**Comment by aldafu** [comment]
Usually a bug like this would warrant a new release. Now there are two different 3.2.0 release tarballs. But thanks for fixing it.

**Comment by sanderr2** [comment]
How do I compile the front end assets?!

**Comment by sanderr2** [comment]
Seems like it just needed a directory called dist creating under static
