### ISSUE TITLE
[Feature Request] add MQTT support for changing the location of the scanner

### ISSUE THREAD

**Issue by Bart274** [PokemonGoMap/PokemonGo-Map#145]
It would be great if we could add an MQTT channel which the server monitors to change the location of the scanner. Now we need to open the browser and wait until the location is updated for the scanner and wait until the scanning is done.
My location is tracked by Home-Assistant and I could send my coordinates to my MQTT broker. If the server could read this location, it would be able to start scanning, even before I start the browser. I have a webhook connected to Slack so it would even give me notifications of new pokemon near my current location even without opening the browser first.

## Expected Behavior
Read the coordinates from an MQTT channel and change the location of the scanner

## Current Behavior
Now we need to open the browser and put in the new location (for browser that don't allow the automatic change of location) and wait for the tracking to start.

**Comment by chuyskywalker** [comment]
We're very unlikely to do this. Since updating location is very easy process (it's just an HTTP post) you should be able to add a small application of your own to read incoming data and make the post as needed, then listen for the webhooks to do whatever afterwards.

If you do make this process, though, let us know and we'd love to add it to the wiki for others to know about, but as a core feature it doesn't make sense to add.

Thanks!

**Comment by Bart274** [comment]
@chuyskywalker do you have an example of the HTTP POST that is needed for this to work?

**Comment by Bart274** [comment]
@chuyskywalker I used this `curl -X POST http://localhost:5000/next_loc?lat={{ states.device_tracker.iphonebart.attributes.latitude }}&lon={{ states.device_tracker.iphonebart.attributes.longitude }}` but it didn't work :s
