### ISSUE TITLE
Docker Version of Map issuing Exception while downloading map

### ISSUE THREAD

**Issue by bbdoc** [PokemonGoMap/PokemonGo-Map#1547]
## Expected Behavior

Map should be downloaded and location fixed.

## Current Behavior

Script is reporting below error. Several users have been reporting this issue on the discord help channel and all confirmed they are using the docker deployment of the map.

2016-11-15 08:46:18,678 [ search-worker-0][ search][ INFO] Searching at 50.827954,3.249618 
2016-11-15 08:46:18,701 [ search-worker-0][ search][ WARNING] Exception while downloading map: Error relocating /usr/local/lib/python2.7/site-packages/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found 
2016-11-15 08:46:18,702 [ search-worker-0][ search][ ERROR] Invalid response at 50.827954,3.249618, abandoning location

## Steps to Reproduce (for bugs)

Create a docker deployment and launch map with at least one worker

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): Python 2.7 
* Operating System and version (desktop or mobile): Docker running on Linux

**Comment by benadderson** [comment]
I'm one of the several users reporting this issue. I'm happy to help try things out, if a volunteer is needed.

**Comment by wukken** [comment]
same problem here :)

**Comment by Brownbear1984** [comment]
I also reported this in the discord yesterday this happens if i pull from the frostthefox or pokemap repos. It also happens if i do a docker build from the latest source.

**Comment by onilton** [comment]
It also happens with me. Using Scalingo here. It happens after the commit 2be283810a9bf2e5e38813895971f39ed51a8658. I reverted to the previous commit and everything is working fine.

**Comment by wildwingripper** [comment]
Same problem.;(

**Comment by mxufirst** [comment]
Same problem on docker 
[ERROR] Invalid response at xxx.xx, xxx.xx, abandoning location

**Comment by alexlef42** [comment]
Does anyone have working image for docker?

**Comment by josdesluwe** [comment]
Where can I find a previous version? I have the same problem!

**Comment by wukken** [comment]
i'll try to deploy old api again.

**Comment by bbdoc** [comment]
wukken how can you deploy previous docker version ? Isn't there a risk of getting your workers banned as this would mean reverting back to 0.43 API ? Can't someone help on getting a valid docker image with latest version ?

**Comment by wukken** [comment]
That would be awsome ;) . maybe ill just w8 a little longer then

**Comment by bbdoc** [comment]
yep no idea if this issue is being handled or not. I've been calling for support on the discord several time but received no feedback

**Comment by wukken** [comment]
lets hope they look into it fast :p

**Comment by scooterpsu** [comment]
I'm wondering if it's only notable with docker/docker-ish setups because other installs are referencing lib files they still have, where new installs don't come with them anymore.

If someone else could solve it, I could fix my docker image, but I don't want to just slap things together and hope for the best.

**Comment by josdesluwe** [comment]
@wukken Would be great to deploy the old api. Noone can create a new pokemon go map now. I created mine Saturday around 3PM CET and all still worked fine. None of my accounts got banned.

**Comment by bbdoc** [comment]
@josdesluwe How do you rollback docker image to a previous version ?

**Comment by wukken** [comment]
i dont know. He created it before api update i guess @bbdoc @josdesluwe

**Comment by josdesluwe** [comment]
@bbdoc I'm not an expert, sry don't know...

**Comment by bbdoc** [comment]
@josdesluwe As I understand you are still running on the previous version and it's working fine, can't you save your docker image for us and put it somewhere on an ftp or dropbox or something similar. That would allow us to load it back and have a temporary solution while awaiting a fix on the latest version ?

You should be able to save your image using : docker save -o <save image to path> <image name>

Thanks

**Comment by joaosreis** [comment]
The problem is that Alpine doesn't have glibc which the new API uses. I modified the Dockerfile to use Debian instead of Alpine and it's working perfectly. See below:
`# Basic docker image for PokemonGo-Map
# Usage:
#   docker build -t pokemongo-map .
#   docker run -d -P pokemongo-map -a ptc -u YOURUSERNAME -p YOURPASSWORD -l "Seattle, WA" -st 10 --gmaps-key CHECKTHEWIKI

FROM python:2.7

# Default port the webserver runs on
EXPOSE 5000

# Working directory for the application
WORKDIR /usr/src/app

# Set Entrypoint with hard-coded options
ENTRYPOINT ["dumb-init", "-r", "15:2", "python", "./runserver.py", "--host", "0.0.0.0"]

# Set default options when container is run without any command line arguments
CMD ["-h"]

COPY requirements.txt /usr/src/app/

RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
 && pip install --no-cache-dir dumb-init \
 && pip install --no-cache-dir -r requirements.txt \
 && apt-get purge -y --auto-remove build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY package.json Gruntfile.js /usr/src/app/
COPY static /usr/src/app/static

RUN apt-get update && apt-get install -y --no-install-recommends build-essential curl \
 && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
 && apt-get install -y --no-install-recommends nodejs \
 && npm install \
 && npm run build \
 && rm -rf node_modules \
 && apt-get purge -y --auto-remove build-essential nodejs \
 && rm -rf /var/lib/apt/lists/* 

# Copy everything to the working directory (Python files, templates, config) in one go.
COPY . /usr/src/app/`

**Comment by Brownbear1984** [comment]
The above worked for me although it seems a bit overkill as the image is now 800MB+ compared to the old builds which are around 200MB

**Comment by joaosreis** [comment]
I'll further investigate on how to run binaries linked against glibc on Alpine Linux, but for now this is a workaround.

**Comment by bbdoc** [comment]
@joaosreis looks good but as I'm not a specialist at all, how do I get this setup working ? I usually simply pull the docker image from docker repository (docker pull frostthefox/pokemongo-map). 

How do I create my own docker image ? Simply put your script in a .sh file and execute ? Btw, I'm not on Debian... 

Or can you add this to the docker repository ?

Thanks

**Comment by Brownbear1984** [comment]
I'm trying to build using the below at the moment will let you know if this works

`https://github.com/sgerrand/alpine-pkg-glibc/blob/master/README.md`

**Comment by bbdoc** [comment]
@joaosreis I tried building an image using your DockerFile but ended up with an error... What am I missing ?

Sending build context to Docker daemon 3.072 kB
Step 1 : FROM python:2.7
2.7: Pulling from library/python
386a066cd84a: Pull complete
75ea84187083: Pull complete
88b459c9f665: Pull complete
1e3ee139a577: Pull complete
729baab2cba2: Pull complete
be05488256c3: Pull complete
6721fa748dcf: Pull complete
Digest: sha256:ef77ed1473ac3be3f7143d2007a62ddd63780f316ad1bdff18cd48e495cbc5c3
Status: Downloaded newer image for python:2.7
 ---> d91d61d657d2
Step 2 : EXPOSE 5000
 ---> Running in d5dcddea57f2
 ---> c4c8a67ab0df
Removing intermediate container d5dcddea57f2
Step 3 : WORKDIR /usr/src/app
 ---> Running in f869c7a93a65
 ---> 30a2ecbe8e8f
Removing intermediate container f869c7a93a65
Step 4 : ENTRYPOINT dumb-init -r 15:2 python ./runserver.py --host 0.0.0.0
 ---> Running in 19fa57e87bc5
 ---> cd4f8622c65b
Removing intermediate container 19fa57e87bc5
Step 5 : CMD -h
 ---> Running in 9ec219b3139e
 ---> 368d395e6d30
Removing intermediate container 9ec219b3139e
Step 6 : COPY requirements.txt /usr/src/app/
lstat requirements.txt: no such file or directory

**Comment by joaosreis** [comment]
@bbdoc you must clone this repository, overwrite the Dockerfile with the one I provided and run the docker build command inside the report directory

**Comment by lonelyarcher** [comment]
I made and pushed joaosreis's modified 800mb image to lonelyarcher/pokemongo-map
Unfortunately, I met some error like "Exception while downloading map: seems your IP Address is banned...". I think my Azure vm maybe blocked. 
You guys can try my image if you like, let me know if it works.

**Comment by bbdoc** [comment]
@joaosreis Thanks it worked indeed (even if I get some warnings). Is it supposed to create a new docker image or update the existing one (frostthefox/pokemongo-map) ? I don't see any new image so tried to launch using my usual docker command but still get the same error. 

`2016-11-16 21:04:36,544 [ search-worker-0][        search][ WARNING] Exception while downloading map: Error relocating /usr/local/lib/python2.7/site-packages/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found`

Sorry for those probably stupid question, don't know much about docker and trying to learn :-)

**Comment by joaosreis** [comment]
On your run command, instead of frostthefox/pokemongo-map use lonelyarcher/pokemongo-map
Em 16/11/2016 21:06, bbdoc <notifications@github.com> escreveu:@joaosreis Thanks it worked indeed (even if I get some warnings). Is it supposed to create a new docker image or update the existing one (frostthefox/pokemongo-map) ? I don't see any new image so tried to launch using my usual docker command but still get the same error. 

2016-11-16 21:04:36,544 [ search-worker-0][        search][ WARNING] Exception while downloading map: Error relocating /usr/local/lib/python2.7/site-packages/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found

Sorry for those probably stupid question, don't know much about docker and trying to learn :-)

**Comment by bbdoc** [comment]
@joaosreis YES !!! Working fine. Thanks a lot for your support !

**Comment by ceridan13** [comment]
I get the same error (Exception while downloading map: Error relocating /usr/local/lib/python2.7/site-packages/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found) when I run my map deployed on Jelastic. Is there any solution for that?

**Comment by Brownbear1984** [comment]
So I've been trying to build this using Alpine with glibc included but for some reason it still gives me the same error. Does anyone know if there are any other dependencies?

**Comment by bbdoc** [comment]
@joaosreis Sorry to annoy you again, but is there any way I can integrate a Pull Request into my docker implementation ? (e.g. I would like to add #1526). Thanks

**Comment by Brownbear1984** [comment]
stop and remove your old container and run the same command you used to deploy it but this time replace "frostthefox/pokemongo-map" with "lonelyarcher/pokemongo-map"

**Comment by bbdoc** [comment]
OK, tried to update but still don't see 1526 in it. How do I add a PR into my docker ? Thanks

**Comment by Brownbear1984** [comment]
It's not really that sole buddy. You'll need to download the source and build your own docker image and then deploy it. The captcha pr is definitely in the lonelyarcher build, I'm using it myself. I'd assume you are either not specifying the correct image in your docker command or you have passed the correct arguments to the container to enable the captcha

**Comment by onilton** [comment]
I get

```2016-11-19 22:41:24.408699778 +0100 CET [web-1] [stderr] 2016-11-19 21:41:24,407 [ search-worker-1][        search][ WARNING] Exception while downloading map: python: undefined symbol: encrypt```

When using @joaosreis Dockerfile . Any ideas?

**Comment by Oxyde59** [comment]
Hi all,

the last release still have the problem :(
Exception while downloading map: Error relocating /usr/local/lib/python2.7/site-packages/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found

Lonelyarcher, could you update ? Or anyone could commit the alpine / python fix ?

**Comment by lonelyarcher** [comment]
I updated the image today.
@Oxyde59, I don't think your problem is from the out-date release. Make sure to replace "frostthefox/pokemongo-map" with "lonelyarcher/pokemongo-map"

**Comment by Oxyde59** [comment]
Yes, it's OK with your release, but not with the "official" one

**Comment by bbdoc** [comment]
@lonelyarcher How do I pull a PR inside my docker image ? I would like to use spawnpoint scanning on my map to reduce accounts (and thus captchas) but need to pull a PR for this (probably 1530). Thanks

**Comment by lonelyarcher** [comment]
@bbdoc  git clone https://github.com/PokemonGoMap/PokemonGo-Map.git and pull

**Comment by bbdoc** [comment]
@lonelyarcher To make sure I don't make any mistake and understood you well (sorry, need a "for dummies" guide), I need to : 
- Clone PokemonGo-Map Repository
- Pull PR 1530 (using usual pull commands)
- Overwrite Dockerfile with the one @joaosreis provided above
- Run docker build command
This should build a docker image including PR 1530
Correct ?

**Comment by lonelyarcher** [comment]
@bbdoc  yes, and you can upload your image to dockerhub to share

**Comment by wukken** [comment]
So did anyone actually made it work of jelastic ?

**Comment by Oxyde59** [comment]
Yep, me.
All u need is above

**Comment by ceridan13** [comment]
thanks, guys!

**Comment by Ausscientist** [comment]
@lonelyarcher first time poster. I was really glad to find this thread which solved the issue i was having after having not been on maps for a long time.

Is there any possibility that you might update your docker file lonelyarcher/pokemongo-map to include the newest builds (particularly i would like to use -speed function) with the Debeian instead of the Alpine?

I have tried discord but am not getting much help there.

Thanks alot

**Comment by bbdoc** [comment]
@joaosreis Sorry to bother you again. I have been using your dockerfile since then, but I'm now trying to use screen inside my docker so I could access -ps page on my instances. I have been looking all around and couldn't really manage to have screen included in my DockerFile. Do you happen to know how I could achieve this ? Thanks

**Comment by FrostTheFox** [comment]
I wish I would've been notified of this earlier, lol.

I replaced the dockerfile in the official repository, and the docker build is pending. Everything *should* work fine in the normal frostthefox/pokemongo-map once that build finishes.
