### ISSUE TITLE
[Feature Request] Get a list of Gyms for a specific Account

### ISSUE THREAD

**Issue by bbdoc** [PokemonGoMap/PokemonGo-Map#1624]
I think it would be interresting for lots of people if we could get a list of gyms a specific Account is in, together with a full view on what pokemons are currently in those gyms, as well as lvl and XP points of the gym. All info is in the DB, so I guess this could be built quite easily.

I see it as a sidebar in which I could input an account name in order to perform a scan on gym infos and return a personal list of owned gyms.

Would really appreciate to see this implemented ;-)

**Comment by Oxyde59** [comment]
Ho yes, I want that.
Or just see the player's name in a gym !

**Comment by bbdoc** [comment]
@wobblybobz Just thinking about this... With you sidebar being commited, wouldn't it be easy to simply add a search field on top of the sidebar where user could input an account name and get the map filtered with this account name ? Would totally fit my need here and looks pretty straightforward (but i'm not a specialist of course, maybe I'm overseeing that). Thanks

**Comment by Hydrargyrum-Wells** [comment]
What would people do with that information?

**Comment by jane0815** [comment]
If it is owned by a ENL or other people we don't like we can go there and smash it!

**Comment by slagell** [comment]
Or even remembering where you have placed them all. :-)

**Comment by bbdoc** [comment]
@slagell Sure, and I could probably also remember spawns points in my region, why do we need a map ?

But I do agree with @jane0815's comment, didn't think this way but this could indeed be used the wrong way.

**Comment by sebastienvercammen** [comment]
This feature would be abused for witch hunts, when people assume someone is botting/cheating because they are losing to them in-game. It also doesn't add any real game or social value, since the game isn't about hunting a specific person, it's just about doing what you can in your local area, which is why I'm rejecting the request.

That being said, anyone with a good enough reason for this data will have enough dedication to write the query themselves.
