### ISSUE TITLE
Feature Request  hash service from honorbuddy

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoMap/PokemonGo-Map#1655]
https://honorbuddy.myshopify.com/products/hashing-service-150-rpm 

is support for this planned? it is quite less expensive than the 2captcha option...

**Comment by catnet23** [comment]
@PeshBG no it's not. a paid API would not be supported.

**Comment by forcewill** [comment]
@catnet23 2captcha is a paid api and supported, the issue here is this would be supporting bots. 
I'm concerned however with pogo map future...

**Comment by PeshBG** [comment]
i dont care for bots(except for making an account lv 10 for the 2 lures to use) but i and most of the people i play with need the map. captcha is way 2 heavy this days and 2captcha is a bit expensive for us to use(if we spend 1$ a day for it that is 15% of the minimum income in our country) at some point 0.45 will be stopped and with it the map ...

**Comment by catnet23** [comment]
@forcewill yes you're right. Sorry, some language issue.
@PeshBG thats poor but, it will not be supported.

**Comment by WalterMagnum** [comment]
If the devs of the main branch don't add this support, I am sure someone will fork it and implement it.  I don't understand the attitude of not supporting Bossland.  They were a multi-million dollar company before PoGo was even thought of.  Our measly hashing $ will be a drop in the bucket for them.  We are only hurting ourselves by boycotting them.

**Comment by FrostTheFox** [comment]
Yes, it will not be added in this branch. @WalterMagnum My morals are not about supporting botting. We've been against them since the start, and I'm not going to directly support them now. The repo will continue until Niantic stops accepting old requests, and, then we will likely shut it down. There will be information posted in Discord and the readme will be edited here when said time comes.

It's true someone will fork it, which I have no problem with, that's the beauty of open source, but the point is I wont be a part of it. You have to put your morals first sometimes. I enjoy bringing it to everyone and all the people in Discord, but PokemonGo-Map honestly is not enough for me to start supporting botting.
