### ISSUE TITLE
[Feature Request] Add support for PokeFarms 0.51.0 API Hashing

### ISSUE THREAD

**Issue by MikeShiner** [PokemonGoMap/PokemonGo-Map#1668]
PokeFarmer (and other REs) have released the hashing secret for the latest 0.51.0 API . It however, is a subscription-based model in which you get a certain amount of Requests Per Minute through their service.

Pricing is somewhat reasonable and since PokeAlert (Android) employed it - I've run over 150 account from a single IP for 2 hours nows with only 2 Captchas. The cost of using the new API outweighs the cost of Captcha solving so I would really like support for this added to the Map if possible.

See more here: https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by sebastienvercammen** [comment]
This has been discussed extensively on our Discord (and is still being discussed). More news coming today, with a final announcement in our #announcements channel tomorrow.

Also closing, because it's currently not going to happen for a multitude of reasons.

If you want to add feedback or do want it implemented, make sure to head over to our Discord for the next 2 days.
