### ISSUE TITLE
Significantly less Pokemon showing up on scan

### ISSUE THREAD

**Issue by Crazy-Clown** [PokemonGoMap/PokemonGo-Map#204]
Hey Everyone.

I've just got the develop version running on my box with 8 Google accounts, using a scan delay of 10, and radius of 6 and I'm noticing a very low find rate.

Can anyone confirm this to be accurate?  Have you noticed a difference from this Fork compared to the original AHAAAAAAAA release of PokemonGo-Map?

I'm 100% there's something weird going on here, the starting map location I have (my primary one) always has pokemon around its area.  Two of my accounts have found nothing (top left of screenshot).

https://postimg.org/image/ryv2btcb9/

Any ideas?

**Comment by drewreece** [comment]
Disable the other accounts, run the command manually for each account, view the output in terminal or in the logs. You may have workers that are failing due to bad accounts, unverified status etc.

I wouldn't be surprised if you are banished to the reddit, this is not a  support forum…
http://reddit.com/r/pokemongodev/

**Comment by Crazy-Clown** [comment]
> Disable the other accounts, run the command manually for each account, view the output in terminal or in the logs. You may have workers that are failing due to bad accounts, unverified status etc.

All accounts are verified, have been logged into, ToS accepted and are working.  I thought there may be some sort of issue with the build because of the noticeable difference in results.  I'll take my question to Reddit, thanks for response.
