### ISSUE TITLE
Installation from git clone fails to find requests module when running runserver.py even if it is installed

### ISSUE THREAD

**Issue by tristaoeast** [PokemonGoMap/PokemonGo-Map#230]
```
$ python ./runserver.py 
Traceback (most recent call last):
  File "./runserver.py", line 10, in <module>
    import requests
ImportError: No module named requests
```

## Your Environment

* Version used: git clone of develop branch
* Environment name and version (e.g. Python 2.7): python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by BaIthamel** [comment]
Troubleshooting on discord

**Comment by tristaoeast** [comment]
Sorry. Didn't know that, where's the discord link?

**Comment by t2ac32** [comment]
had the same problem how did you solve it ?

**Comment by rockerhieu** [comment]
@t2ac32 you can try:

### Uninstall all requirements
`sudo -H pip uninstall -r requirements.txt`

If the above command is failed because some of the libraries aren't installed then you can go through the list in requirements.txt and uninstall one by one using: `sudo -H pip uninstall <lib_name>`

### Reinstall al requirements
`pip install --upgrade -r requirements.txt`

### Run the server

`python runserver.py` but not ~~`./runserver.py`~~
