### ISSUE TITLE
Location doesn't seem to follow you anymore while in mobile

### ISSUE THREAD

**Issue by Imoq** [PokemonGoMap/PokemonGo-Map#343]
I was using a release from Sunday morning (commit bea23ba3ed722768a674694bc7380da5ee74b54b for what I can see), and when I opened the map via web on Chrome for iPhone, it always followed my location.

I updated to some hours ago version (commit 46cf2e483c524754379d234c37acec3345badcee) and today that I was out, the location mark no longer followed me anymore. Yes, I gave permission to Chrome to use my location, and Options -> Location Settings -> Scan follows location was on as usual.

I still could manually move the red location mark to scan a new area as I was moving, but it was kind of difficult when I didn't know where I was exactly. Not even a browser reload or clicking on Google map location map seemed to help, the red location mark was always pinned to wherever I left it last time and it never followed me.

**Comment by RatedDS** [comment]
I'm also having this problem, not working neither on Chrome or Firefox for PC nor on Chrome for Android.

The device is getting the location properly since I can see the blue dot, but the red marker doesn't follow it and keeps scanning in the last location unless I move it or manually type a location.

Also, I'm still not really sure about what "Scan follows location", "Start at user's location" and "Search" actually mean, specially in terms of several people using the map at the same time in different locations.

**Comment by Imoq** [comment]
@BaIthamel : could you please let me know what issue is this duplicate from so I can follow it? Thank you!

**Comment by gine78** [comment]
I have the same problem. Where is the duplicate?
