### ISSUE TITLE
npm install fails at sass:dist vendor not found on ubuntu 16.04

### ISSUE THREAD

**Issue by yipcma** [PokemonGoMap/PokemonGo-Map#366]
npm install fails at sass:dist vendor not found on ubuntu 16.04

## Expected Behavior

npm install should just work and build.

## Current Behavior

npm install aborted at sass:dist

## Possible Solution

``cd node_modules/node-sass && npm install``
works; but how would one know in the first place?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Running "newer:sass:dist" (newer) task
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/home/andrew/PokemonGo-Map/node_modules/node-sass/vendor'
Warning: Task "sass:dist" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

**Comment by brandonshults** [comment]
Does "npm rebuild sass" from inside the directory with package.json work?

**Comment by CptMonkeyFist** [comment]
I just ran into this problem. The reason is because when you install the "nodejs" package in Ubuntu, it uses "nodejs" as the command for compiling node scripts instead of the usual "node" command. This should be posted as a bug for that package. The sass program has a post build script that runs a node script using the "node" command which isn't found in Ubuntu. 

To fix your problem you need only create a symbolic link like so
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
