### ISSUE TITLE
Add Redis support

### ISSUE THREAD

**Issue by johnkernke** [PokemonGoMap/PokemonGo-Map#414]
It would be great to save on some HDD writes by using Redis (or something similar). SQL isn't really needed for anything that is happening in the database as is, so a plain key value store might be worth while.

**Comment by imynwulf** [comment]
Feel free to make a PR with the change you wish to see.

**Comment by chuyskywalker** [comment]
There are a few pages that need sql power (the stats pages, and heatmaps for example). So I don't know if this is something realistic to entertain.

There was a issue around here somewhere about running sqlite as `in memory` which would be near as effective...

**Comment by toolpunk** [comment]
I actually started working on Redis support for fun. I'm making decent progress but it's not trivial to keep everything in line with this project's design decisions.

I've settled on redisco as my ODM now and am doing some monkey patching to make it work with existing structures. I still need to clean up a bunch of code and do some serious testing. Might be another week or two.

Why would the stats require SQL?

**Comment by toolpunk** [comment]
Update: I have basic Redis support working. The server has been running stable and without errors for a couple of hours now.

**Comment by johnkernke** [comment]
Care to put it into a PR, maybe someone else can give you a hand at fixing it up.

**Comment by toolpunk** [comment]
I was able to improve it significantly already, but this is about as fast as it gets with redisco. It's just that you can't query like you would in SQL. The first couple of search steps are way faster than mysql/sqlite, but it becomes increasingly slower with every step.

You end up pulling more data then you need, then have to filter out what you want and convert it to dicts. I don't think there's any reason for a PR, because while interesting it just isn't good enough.

I've come to the conclusion that redisco might not be the right tool for the job, so I'm writing my own redis-py code now.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
