### ISSUE TITLE
Hex-Beehive generation

### ISSUE THREAD

**Issue by DeastinY** [PokemonGoMap/PokemonGo-Map#476]
I feel like I'm doing something really wrong here, but I always end up with shapes like this :

![2016-08-11 09_07_06-pokemon go map](https://cloud.githubusercontent.com/assets/5399476/17583905/db3457d4-5fb3-11e6-9c79-ebfe82567d8b.png)

The command I used was `python location_generator.py  -lat 50.8 -lon 6.1 -st 3 -lp 7 --accounts accounts.csv
`

Any help would be appreciated. There are about 60 processes running for that, is that intended ?

![2016-08-11 09_18_54-ric hs-se-ric_ _git_pokemongo-map](https://cloud.githubusercontent.com/assets/5399476/17584194/864026e8-5fb5-11e6-885b-42cafff7d5af.png)

**Comment by daaaaa** [comment]
Well, if you use lp = 7, you will have something like 169 workers. It is normal having more than 60 processes. If I did the right calculation you should have

lp | workers
1:        7
2:        19
3:        37
4:        61
5:        91
6:        127
7:        169
8:        217
...

Do you have 169 accounts in your file?

**Comment by DeastinY** [comment]
Thanks for the clarification. I have about 30 accounts, so I'll try lp=2

**Comment by daaaaa** [comment]
Since you have more than 19 account, you can enable multithreading and the script will automatically add the remaining account to the first 11 locations. In such a way you will have for the first 19 location 2 accounts (doubling the search speed), while for the next 8 location only 1 account.

To enable multithreading simply add -t 2 to your string:
`python location_generator.py -lat 50.8 -lon 6.1 -st 3 -lp 2 -t 2 --accounts accounts.csv`

**Comment by DeastinY** [comment]
nice ! Thanks for the hint :)
How does the process count correlate to the accounts used ? running the hive with `-lp 2` ends in 4 processes running. Are those 4 processes really using 19 accounts ?

**Comment by schawsk** [comment]
Does multithreading now owrk on windows too, or is that still broken?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
