### ISSUE TITLE
Add option to increase scan point distance

### ISSUE THREAD

**Issue by Mantriur** [PokemonGoMap/PokemonGo-Map#72]
It would be great to be able to influence the spacing of the scanned map points, or to toggle the distance from the pokemon detection radius to that of gyms and pokestops. That way one could have a separate scanning task keeping a large area of gyms up to date.

**Comment by TheRealGitCub** [comment]
Is what you're describing different from what can be done using `-st`?

**Comment by JZ6** [comment]
1. If by spacing you mean increase the space between each step, have fun missing that 100 iv dragonite in those spaces.

**Comment by Mantriur** [comment]
No, st defines the amount of scan points from the current position. I mean the distance between those.

@JZ6 It's not for scanning pokemons. It's to have a supplemental scanning task keeping a larger area of gyms up to date, because they are reported over a far longer distance than pokemons.

**Comment by BaIthamel** [comment]
This is not an issue it's a feature request. Please don't use the *issues* tab for requests.

**Comment by TheRealGitCub** [comment]
Isn't that one of the purposes of the Issues tab on GitHub and the reason that the enhancements tag is there by default?

**Comment by chuyskywalker** [comment]
I think this is a legitimate, but sorta naunced, request.

Essentially, we can only get 70m worth of pokemons per scan point, but the gyms/pokestops show much, much further away points.

If you could setup a thread to change our algorithm for each step from 70m to, say, 500m, the same `-st` value would cover a much, much larger area of gyms/pokestops.

This _can_ be achieved right now by adding a ton of `-st 1` threads, but that'd be rather tedious.

**Comment by chuyskywalker** [comment]
In fact:

with the normal 0.070 (70m step):

![2016-08-07 22_08_47-pokemon go map](https://cloud.githubusercontent.com/assets/131800/17469850/04d9f87a-5cec-11e6-8d36-91f88223502c.png)

Hack that value over to 0.500 (500m) and FWOOSH:

![2016-08-07 22_10_05-pokemon go map](https://cloud.githubusercontent.com/assets/131800/17469853/11ad0010-5cec-11e6-9f3d-40039bfcff8a.png)

Way, WAY more gyms/pokestops, zero extra server load.

**Comment by JZ6** [comment]
so we

**Comment by chuyskywalker** [comment]
Nah, just add an option that let's you futz with the point distance between steps for just the python code*. Something like `--step-length` with a default of `0.070`. Then a person could run the main app normally, but start an extra `-ns` thread with a way higher `--step-length` to cover the wider area of gyms/pokestops.

_\* You don't want the JS code to follow suit, otherwise the green "scanned area" circles would cover the whole area and a ton of people would think that we somehow are missing a tone of pokemons...._

**Comment by JZ6** [comment]
^seems like a cool addition but useful ness might be limited.

**Comment by blindreaper** [comment]
Will there be a benefit other than pokestop/gym update speed? Will it reduce cycles/data or anything if a dedicated thread is used for stops/gyms only? I've never tried no stop/no gym options.

**Comment by Mantriur** [comment]
The regular scan also catches gyms and in a wider area, too. This is neat if you'd like to have, say, an updated view of all gyms in your city, without requiring 20 accounts.

This is fairly simple, already added it, but can't test, because the front end doesn't seem to work. Did Google pull the plug on the maps?

**Comment by karololszak** [comment]
I did it on my private fork, max distance to not losing any pokestop/gym is 1km (1000m), but I use `pulse_radius = 0.999` because the script was freaking out when it was an integer (I am no python developer but maybe I should've used `1.0` instead of `1`, but `0.99` works for me :P).

I also wrote in the PR about changing the scan radius on the frontend.

**Comment by Goldvivi1** [comment]
+1

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
