### ISSUE TITLE
-ss doesn't follow your location marker, it always scans around starter location

### ISSUE THREAD

**Issue by Imoq** [PokemonGoMap/PokemonGo-Map#755]
## Expected Behavior

Whenever you move your map marker to a new location, -ss scan should start scanning the points around that given location taking into account -st value. You can always use a bigger -st value but when you have notifications around the area you are (via PokeAlarm or others) then you don't need to know a rare Pokémon appeared very far away.

## Current Behavior

If you move your location marker in map, log realizes about the new location but it continues scanning around the original coordinates instead of moving and scanning around your new position.

## Possible Solution

Re-start a scan around the new location on map taking into account -st value every time the man marker moves.

## Steps to Reproduce (for bugs)

1. Start a worker with -ss
2. Notice the scans appearing around you - great!
3. Move your marker to some other part of the map, wait few minutes.
4. Notice that, even if you see on console log that a new location was detected, scan is still made around the original location instead of now being around you.

## Context

I usually am at home and working with -st 5 on the radar during the day, but on the evenings I go out and walk around the city and expect to find the Pokémon around where I am, not around my house!

## Your Environment

* Version used: commit 7cdb8c1ec3af5eda258dadc9f8c6f2095988f202
* Environment name and version (e.g. Python 2.7): Python 2.7 
* Operating System and version (desktop or mobile): Raspberry Pi (Jessy)

**Comment by justsomedudeonthenet** [comment]
I don't think you understand how the spawnpoint scanning mode works.

Once your database has sufficient information, you know exactly where pokemon will spawn, and at what time.  You aren't supposed to be doing step searches or beehives anymore with it, it just scans the exact location where a pokemon will spawn.

So there is no need to move the location, and no step size to worry about.

If you still want a step based scan around your location, start a separate instance without the -ss.

**Comment by Imoq** [comment]
I do understand how it works, I don't care about doing beehives or step searches. I just want to be aware and notified of *close* Pokémon that spawn near my *current* location (within a radius of, for example, 750 m around where I am located) so I get notified via PokeAlarm or other notify method when an important Pokémon spawns nearby.

If the spawn scan doesn't "follow" your location, and you move 4 km. away from the center of the scan, you will be notified for a pop very far away instead of the close ones.

I prefer -ss over original method / beehive because it picks up the spawns at 13-14 minutes which is more than enough time to go running to get the Pokémon, but only if you are nearby.

I apologize if I didn't explain it well, I hope this can be understood.

**Comment by justsomedudeonthenet** [comment]
Spawn scan mode doesn't follow your location at all, ever.  The only thing it uses the specified location for is right at startup, to build a list of spawnpoints, and even that only happens if you don't already have a spawns.json file.

But, I do understand wanting to be notified only about things that are close to you.  There are two ways of handling that:

- Have a separate copy of PokemonGo-Map running that does the normal scan method and can be moved around.  It can share the same database, so spawns from both instances will show up properly.  Only give this copy the webhook to tie into PokeAlarm.
- Use this PR on pokealarm: https://github.com/kvangent/PokeAlarm/pull/117, which allows you to move the location that PokeAlarm is notifying about.  Set your ranges in PokeAlarm to whatever you are willing to walk/drive to.  Use the new /location URL to update your location.

**Comment by Imoq** [comment]
Oh, thank you for taking the time to explain this to me. I understood otherwise because if I just run

`python runserver.py -ss`

It will only scan the spawn points around the "step-limit: " on my config file (which is 5 currently) starting on "location:" even if I have "mapped" the spawn spots on many parts of the city I have been to in the last days.

Definitely both your suggestions are worth looking at and I think I'll stick to one of them. In any case, what worries me is that if I want to cover a good chunk of the city with so many spawn points around, the only 3 accounts I have running would be fast teleporting everywhere, even if on the second worker (or via PokeAlarm fence) I would only be needing to be aware of the spawns in a reduced (but mostly moving) small area of the city, around the size of 5 steps.

I still find value in only scanning spawn points around the area you are moving, to avoid both unneeded queries to Niantic servers (that, again, I know were greatly reduced by only scanning one pop spot every 15-ish minutes) and also potential bans for moving around everywhere in the city when you only need to be focused on a very small area.

Would it be very hard to implement something like this? I know the script already establishes a scanning area when it starts and moves only between the spawn spots in that area. Would it be very hard to be able to have this changing dinamically?

Thank you!

**Comment by justinkwaugh** [comment]
It could be modified to follow you around no problem, but it would obviously only be effective if you had already mapped the spawn points (which it sounds like you have)

**Comment by tboyce1** [comment]
You might be able to try #737. I don't know if it re-triggers the calculation for which spawn points to scan though but if it does then you might be able to just change the location and toggle it off and on.

I definitely agree that this is something that should be considered though. I'd prefer to just use one or two accounts at a time and scan a small area around me than use 10+ to scan every area I might go to. That way I only risk getting one account banned at a time and can easily move to the next one rather than having them all banned at once and having to find a way to make a bunch more.

I have to imagine scanner accounts are the easiest for Niantic to detect... How many hours have you played or Pokemon have you seen? A lot. How many Pokeballs have you thrown or Pokestops have you visited? Zero. Ummm...

**Comment by Imoq** [comment]
@justinkwaugh great! I hope somebody with the right knowledge gets interest on this feature request :)

Thanks, @tboyce1 , I'll definitely check it out tomorrow!

**Comment by Stupefy** [comment]
also toggling search on or off does nothing when in -ss

**Comment by BaIthamel** [comment]
This is not  feature request location, please use the feathub (I +1 this tho)

**Comment by Imoq** [comment]
Understood and than you. Created a feature request here: http://feathub.com/PokemonGoMap/PokemonGo-Map/+60
