### ISSUE TITLE
Halt after one worker possible account ban

### ISSUE THREAD

**Issue by FlarumHostingCo** [PokemonGoMap/PokemonGo-Map#827]
Console shows 1 worker suddenly banned and everything comes to a halt after.   Restarting runserver.py results same issue
2016-08-18 21:47:49,032 [ search_worker_2][        models][    INFO] Upserted 1 pokemon, 175 pokestops, and 14 gyms
2016-08-18 21:47:49,106 [ search_worker_1][        models][    INFO] Upserted 0 pokemon, 180 pokestops, and 14 gyms
2016-08-18 21:47:49,184 [ search_worker_5][        models][    INFO] Upserted 0 pokemon, 182 pokestops, and 15 gyms
2016-08-18 21:47:49,184 [ search_worker_4][        models][   ERROR] GET_MAP_OBJECTS response has 0 items - ! Username: xxxxxxxxxxxxxxxxxxxxxx

then just hangs open here and no Pokemon on map

Ubuntu 16.4, MariaDB 10.1, latest requirements.txt

**Comment by n3cr0cr0w** [comment]
When did you last pull down changes?

**Comment by FlarumHostingCo** [comment]
Latest dev branch pull and using this I found in a issues thread..  Was working up until tonight

$ git diff
diff --git a/pogom/models.py b/pogom/models.py
index 602bdf7..3a55e9a 100755
--- a/pogom/models.py
+++ b/pogom/models.py
@@ -3,6 +3,7 @@
 import logging
 import calendar
 import sys
+import time
 from peewee import SqliteDatabase, InsertQuery, \
     IntegerField, CharField, DoubleField, BooleanField, \
     DateTimeField, CompositeKey, fn
@@ -317,12 +318,17 @@ class Versions(flaskDb.Model):
         primary_key = False


-def parse_map(map_dict, step_location):
+def parse_map(map_dict, step_location, username):
     pokemons = {}
     pokestops = {}
     gyms = {}
     scanned = {}

+    if len(map_dict['responses']['GET_MAP_OBJECTS']) == 0:
+        log.error('GET_MAP_OBJECTS response has 0 items - Possible Account Ban! Username: %s', username)
+        log.info('Pausing thread indefinitely')
+        while True:
+            time.sleep(1000000)
     cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
     for cell in cells:
         if config['parse_pokemon']:
diff --git a/pogom/search.py b/pogom/search.py
index 08a75cc..25eb42c 100644
--- a/pogom/search.py
+++ b/pogom/search.py
@@ -251,7 +251,7 @@ def search_worker_thread(args, account, search_items_queue, parse_lock, encrypti
                     # Got the response, lock for parsing and do so (or fail, whatever)
                     with parse_lock:
                         try:
-                            parse_map(response_dict, step_location)
+                            parse_map(response_dict, step_location, account['username'])
                             log.debug('Search step %s completed', step)
                             search_items_queue.task_done()
                             break  # All done, get out of the request-retry loop

**Comment by Rikilsta** [comment]
it stopped working for me today

**Comment by ultrafunkamsterdam** [comment]
I have 4 banned accounts in one week. 

One account was my own personal thread/server.. nothing special (-st 5 -sd 10). Possible due to moving marker (counts as teleport).... how do they measure it? If i'm in the car,  got the app open, put my phone to standby or flightmode, and 5 kilometers ahead and unlock my phone, it is 'teleported' too (to my logic). Because the app does not have any connection or GPS coordinates on the background, it just comes up and moves quickly to my new location (and still logged in too, which makes me think an actual phone is using listeners (phone.lock; phone.standby; phone.wifi; phone.cell that pauses the app some way, so it not counts as 'teleport'.

One account was banned when used in --scanpoints-only mode.

2 accounts got banned (you can see it in the pic attached) last night in my 2 beehives i set up. All accounts in the 2 hives are doing the same things. -st 5 -sd 10(default).

What could be the trigger to ban? In the hive they're all doing the same thing on fixed positions, started at the 'same' time (2 seconds delay). Why are not all accounts banned if Niantic follows a pattern? Is it ramdom sample account checks?

![image](https://cloud.githubusercontent.com/assets/21027969/17802644/be2ce950-65f1-11e6-9746-caf8f79d7d48.png)

**Comment by DMC90** [comment]
@ultrafunkamsterdam 

I don't know if there is any relation, but my account got banned last night and I was doing scans in the exact same location (kalfjeslaan, amstelveens winkelcentrum and waardhuizen).

I actually installed everything last night, used the same settings  (-st 5 -sd 10) and was really surprised this morning when I noticed the map wasn't working anymore. In my case it's extra f*cked up since they IP banned my server, not just the PTC account...

I might have done some 'teleports' with the location marker, but a friend of mine is doing/did it as well and his map is still working fine.

**Comment by xcheneric** [comment]
Probably has something to do with this commit: https://github.com/PokemonGoMap/PokemonGo-Map/commit/fbbdff2342b1349699ab84ae6da50177f1e02f34

**Comment by nicktan147** [comment]
Not sure if this works, I have been trying to make my map accs act like human behaviour,  instead of immediately after finish tutorial, and start running the map, i will make that account gain some level first
then agree some TOS in the website. Then when I want the marker go somewhere, I make it move like human or driving in car moving. I'm glad, so far all my account has not be banned yet so far.

**Comment by ultrafunkamsterdam** [comment]
@DMC90, Wat is de wereld toch klein :) zeker in niches als dit.

**Comment by fayder** [comment]
Has anybody been able to solve this issue?

**Comment by ultrafunkamsterdam** [comment]
@fayder You need to logon with your phone first, catch a starter pokemon and a pidgey, and even better visit 1 pokestop.

**Comment by fayder** [comment]
@ultrafunkamsterdam Yep, that's confirmed. I tried that and it was OK. Thanks. I think this issue should be closed?
