### ISSUE TITLE
Beehive generator very inefficient

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#84]
I used it with -st 5 -lp 4 (same withh -st 10)
![image](https://cloud.githubusercontent.com/assets/20150243/17472992/49dd3dda-5d4e-11e6-8133-e44525f235a7.png)

**Comment by JZ6** [comment]
..... gotta be honest, never seen something this bad before.

**Comment by stekern** [comment]
I'm having the same problem. 

It does not seem to be dependent on number of accounts per worker, nor does it seem to be because of low processing power (tested on Google Compute Engine with instances running 1-8 vCPUs). 

For me the only way to get less red/yellow spots in the hive, is to drastically limit the number of workers. 

Before the most recent change in API, but after 10s scan delay was introduced, I was able to run the exact same hive with no red or yellow spots. This has led me to believe that there is some kind of bottleneck introduced in the newest fixes (in the encryption library etc.?).

**Comment by Talhoo** [comment]
looks like an updated radius (70m) with a not updated radius in map.js (100m)

**Comment by Zerotask** [comment]
@Talhoo Thank you. I forgot to change the radius to 70m in the map.js.
