### ISSUE TITLE
When installing from GitHub add note to install libsass first

### ISSUE THREAD

**Issue by TheHippo** [PokemonGoMap/PokemonGo-Map#857]
## Expected Behavior

If you follow the instruction from the documentation to install from source on a fresh box you expect everything to work.

## Current Behavior

During `npm install` you rather useless error message. (Something went wrong with `grunt`. Calling `grunt` from `node_modules/.bin` isn't helpfull either.)

## Possible Solution

Install [`libsass`](https://github.com/sass/libsass).

Add a note to the documentation that `libsass` needs to be installed when installing from source.

## Steps to Reproduce (for bugs)

See above

## Context

> How has this issue affected you?

I dug through 25k lines of `npm-debug.log`. This isn't the most enjoyable thing to do. :wink: 

## Your Environment

Linux

The only thing special about my environment is, that I am running an Atom CPU.

```
$ cat /proc/cpuinfo | grep model
model           : 77
model name      : Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
model           : 77
model name      : Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
```

Otherwise:
```
$ node -v
v4.4.7
$ npm -v
3.10.6
$ uname -a
Linux XXXX 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.10
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

**Comment by pyr0ball** [comment]
node-sass installation should be handled by the installation scripts. It's likely that simply needs to be shifted higher up in the node package list.

**Comment by chuyskywalker** [comment]
That package would be installed via [this dep](https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/package.json#L27) -- perhaps you could discover what was peculiar about your setup that made the install fail because, normally, sass will install from this dep list.

Where grunt-sass requires node-sass: https://github.com/sindresorhus/grunt-sass/blob/master/package.json#L34

**Comment by pyr0ball** [comment]
most of the time when this comes up I fix it by running `npm install -f grunt-cli`

we might need to handle it via bash/batch install

**Comment by angrymoose** [comment]
@chuyskywalker i am not sure if that is required or a good idea. As he is running ubuntu 15.10 which has lost all official support as of July 28, 2016. There is no reason to support distros that no longer receive support from there manufacturer.

**Comment by pyr0ball** [comment]
@angrymoose unfortunately there are a lot of "standard" linux distros used by VPS services that we're having to compensate for since the users aren't able to use a more current OS. It's an ongoing process to work out requirements for specific releases, but it's happening.

Either way, confirmed this is not a bug.

Please post in the [Support Forums](http://pokemongo-map.me) for future issues like this.
