### ISSUE TITLE
Got a warning when I run "npm run-script build"

### ISSUE THREAD

**Issue by jerry317** [PokemonGoMap/PokemonGo-Map#87]
![npm](https://cloud.githubusercontent.com/assets/11732549/17473099/33adedd8-5d81-11e6-850c-6dbc6b2abd2c.png)

**Comment by patgi** [comment]
I got also a error with "npm run-script build"



> pogomap@0.1.0 build /data/www/default/test2/PokemonGo-Map
> ./node_modules/.bin/grunt build


module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/www/default/test2/PokemonGo-Map/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by johnkernke** [comment]
you are probably running a version of node that is old. update to something v4 or above.

**Comment by Outpox** [comment]
Consider using [nvm](https://github.com/creationix/nvm) to manage your Node installation and version :+1:

**Comment by Placeto303** [comment]
Hello, I have the same issue. Can you please clarify what you mean by using nvm ?

Thanks !

**Comment by Outpox** [comment]
NVM is an Linux/macOS application which handles Nodejs/io.js versions for you. That's what I use on all my servers to easily update Node. I provided the repo links if you want to install it.  
But you can also install/update Node manually if you prefer to.

**Comment by StarForser** [comment]
Same problem 
![11111](https://cloud.githubusercontent.com/assets/17098307/17474117/04e5cc42-5d5d-11e6-81f7-16fbe2709a97.JPG)

**Comment by patgi** [comment]
I got the same error on ubuntu 14.04LTS

**Comment by Placeto303** [comment]
May the issue really related to node version ?

**Comment by johnkernke** [comment]
considering most people having the issue are using v0.10 or v0.12, yes it is related to node version. i just tested the latest build with node v6.3.1 and it worked without issue.

if you are just installing node from your OS's package manager it will most likely be quite old.

**Comment by Outpox** [comment]
Which is why I suggested using NVM :P

**Comment by JZ6** [comment]
NVM is a good call, but ya update node please

**Comment by HinoReo** [comment]
@JZ6 I've just updated everything and still get this:

> grunt build
Running "eslint:src" (eslint) task
Warning: No ESLint configuration found. Use --force to continue.
Aborted due to warnings.

**Comment by Outpox** [comment]
@HinoReo Well maybe providing the error log might be helpful.

**Comment by HinoReo** [comment]
@Outpox No problem. I got these prior to #105 merging (which fixed the issue by disabling linting task):
`> grunt build`
``
`Running "eslint:src" (eslint) task`
`Warning: No ESLint configuration found. Use --force to continue.`
``
`Aborted due to warnings.`
``
`npm ERR! Linux 4.4.0-31-generic`
`npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"`
`npm ERR! node v6.3.1`
`npm ERR! npm  v3.10.3`
`npm ERR! code ELIFECYCLE`
`npm ERR! pogomap@0.1.0 postinstall: `grunt build``
`npm ERR! Exit status 6`
`npm ERR! `
`npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the pogomap package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     grunt build`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs pogomap`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls pogomap`
`npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /home/spacehug/Projects/npm-debug.log`

**Comment by Outpox** [comment]
Wrap your code between 3 \` such as:  
\`\`\`
my code lays here  
\`\`\`

which will render such as:  
```
my code lays here
on several
lines
```

which will improve readability for multiples lines of code.  

What's your Nodejs version (`node --version`) and npm (`npm --version`) ?

**Comment by HinoReo** [comment]
@Outpox :grin: Yeah, sorry
```
node --version && npm --version
v6.3.1
3.10.3
```

**Comment by Outpox** [comment]
@HinoReo I think I faced the same issue earlier and I made a PR (#151) for it.  
Could you please try doing the following and then retry ?  
`npm install node-sass`
