### ISSUE TITLE
Status page Items Queue ammount with -ss

### ISSUE THREAD

**Issue by zimpixa** [PokemonGoMap/PokemonGo-Map#945]
## Expected Behavior
Queues: X items
where X indicates how many spawnpoints left to be "up to date/time"

## Current Behavior
X inticates TOTAL spawnpoints left in hour

## Possible Solution
Revert this change to state pre search refactor commit merge

## Steps to Reproduce (for bugs)

1.Start runserver.py with -ss spawns.json flag
2.See Queues line
3.
4.

## Context
Adding how much seconds Im behind in scanning doesnt actually say how many spawnpoints there are

## Your Environment
Python 2.7.12
Pip 8.1.2
Ubuntu 16.04

**Comment by zimpixa** [comment]
Also queue start with number of total spawnpoints, instead of current ammount till end of hour

**Comment by justsomedudeonthenet** [comment]
This is expected behaviour since the search.py refactor.

It's why https://github.com/PokemonGoMap/PokemonGo-Map/commit/0448f930832be8123d658bf5e38f77fe86708c40 added to the status screen an indicator of how many seconds behind or ahead of realtime your next queue item is.  That is now the best way to track how well your workers are keeping up.

**Comment by BaIthamel** [comment]
Before this was done we had people complaining their queue was empty and making issues...

**Comment by pyr0ball** [comment]
perhaps the best way to satisfy this is to make the queue more understandable:

[ search queue = starting step 2 of 450 ]

**Comment by Erin6641** [comment]
I have a few questions and I figure this is an okay place to ask because the issue  is relevant to my questions.

1) when using -sd of say 12, that means each worker waits 12 seconds to upsert the next "spot" it knows to scan via time, correct?
2) If the first is correct, what happens if every spawn point in a certain area spawns at the exact same time, would it then be showing some pokemon spawning with less than 15 minutes? EG. 12 (scan delay) * number of spawns that it had to go through first? 6 pokemon spawn at same second, 1 worker, leads to a 1 minute delay, and that would backlog the upserts?
3) I assume both of the above are correct and therefore we only avoid this by having more workers or scanning an area or we just assume we have an area with a "normal" distribution over the full hour?
4) Lastly, what is the point of exporting to the .json file over using the built in db? Which I believe is called pogom.db?

I am sorry if this is an inappropriate place to ask, let me know if I should have asked in a different location.

**Comment by zimpixa** [comment]
I like idea of pyr0ball, but I'd see it like:
Total search items: xxx (total size, that never changes). 
Total scanned items: xxx (sum of searching done) Total skipped items: xxx (Having those 2 in one line allows to analyze skip %)
Queues: xxx search items, xxx db updates, xxx wh items. (only currently in queue)
Overseer: Processing search queue, next item is (<item no.>/<total>) lat/lng @ time (xxx behind/ahead)

**Comment by pyr0ball** [comment]
@Erin6641 post question on the [support forum](http://pokemongo-map.me)
