### ISSUE TITLE
Error Search step map parsed location failed

### ISSUE THREAD

**Issue by aleleiva16** [PokemonGoMap/PokemonGo-Map#948]
While running the map is showing "Error search step X map parsed location failed, retrying in 10 seconds"

**Comment by ETdoFresh** [comment]
Same here

**Comment by alyssii** [comment]
Same here...

I fear my PTC user account has been banned. I used it exclusivly to run this server. After 1 week in service, now it stopped working. :-( 

2016-08-23 04:22:37,135 [ search-worker-0][        search][   ERROR] Map parse failed at 47.380893,8.505867, abandoning location. user123 may be banned.

**Comment by Draag** [comment]
Lots of scanning accounts are going down fast. Lost 10 of 12 today. Need to find out the ban criteria before wasting more time creating scanner accounts at this point.

**Comment by pyr0ball** [comment]
This is not a bug. please post questions like this in the [Support Forum](http://pokemongo-map.me) or on Discord

**Comment by khag7** [comment]
@pyr0ball Isn't this a bug if the account **is valid and not banned** but the scanner is unable to download the data from the server?

If you look carefully, most of these people saying "OMG BAN" is because of the poorly worded error message thrown by this scanner program. "Account is probably banned" is almost always wrong. I can log in with all my accounts just fine using an official pokemon go client on my phone. However, they all fail to scan with this and any other map program. Doesn't that suggest that the api library we are using is wrong again (unk6 again)
