### ISSUE TITLE
Too early for **** (since 901)

### ISSUE THREAD

**Issue by Maersko** [PokemonGoMap/PokemonGo-Map#981]
## Expected Behavior

A worker to scan a new area each Scan Delay or 10 or so secs
## Current Behavior

**Each worker wait at least 30 + 10 seconds for new location to scan.**

Scans a location with Worker 1, then when worker 1 wants to scan after 10 seconds or so it says "2 early" and can set up to a 40 seconds timer
http://prntscr.com/ca61ei
## Steps to Reproduce (for bugs)

1.Get latest develop
2.Install everything
3.Try and scan some places / with ss maybe

## Your Environment

* Version used: Latest develop
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): CENTOS 7

Yes everything is installed as I've ran this map previously, and I'm still using the version JUST before 901 merged and it works fine.

**Comment by Maersko** [comment]
They seem to be increasing STUPIDLY, workers waiting almost 100 SECONDS for a new scan..
http://prntscr.com/ca63kp

**Comment by Slivo-fr** [comment]
If you are on -SS, it will wait for actual spawn to scan

**Comment by Maersko** [comment]
So you're telling me it's because it knows no pokemon is there its waiting?

**Comment by Saprophator** [comment]
Spawnpoint scanning will ONLY scan if the next spawnpoint in time  will have spawned pokemons. With enough workers you will see idle times because there is just nothing to scan at the moment. Although 100 seconds seems a bit much, depending on how many spawnpoints you are scanning. If you are scanning 1000+ spawnpoints there should be virtually no waiting times because there will always be spawnpoints up for scanning.

**Comment by BaIthamel** [comment]
Not an issue.

**Comment by lota7** [comment]
Why wuold you use spawnpoint scanning without even knowing what it does. sheesh
